spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

# JWT 설정
jwt:
  secret: LeetsBackendKx5_93Jv_1Rz_lQwT9pXe3bD7sUaFzYtAbCdEfGhIjKlMnOpQrStUvWxYz
  access-token-expiration: 1800000
  refresh-token-expiration: 1209600000
